name: "Trigger docs.openssl.org deployment"

on:
  push:
    branches:
      - "OpenSSL_1_0_2-stable"
      - "OpenSSL_1_1_1-stable"
      - "openssl-3.*"
      - "master"
    paths:
      - "doc/**/**.pod"
      - "doc/**/**.in"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger deployment workflow"
        run: |
          gh workflow run -f branch=${{ github.ref_name }} deploy-site.yaml
          sleep 3
          RUN_ID=$(gh run list -w deploy-site.yaml -L 1 --json databaseId -q ".[0].databaseId")
          gh run watch ${RUN_ID} --exit-status
        env:
          GH_REPO: "openssl/openssl-docs"
          GH_TOKEN: ${{ secrets.OPENSSL_MACHINE_TOKEN }}
